// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLwNX6Cr8OFRIOeogcM6x_5Sc1F-57nU0',
    appId: '1:359537542451:web:ce042949117f2230c2aa46',
    messagingSenderId: '359537542451',
    projectId: 'parking-pool-48cd9',
    authDomain: 'parking-pool-48cd9.firebaseapp.com',
    storageBucket: 'parking-pool-48cd9.firebasestorage.app',
    measurementId: 'G-EB17N06QSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBir5_44qQdl9jsndvxlpXX6XqHnymqeNw',
    appId: '1:359537542451:android:8868898fc7ab8499c2aa46',
    messagingSenderId: '359537542451',
    projectId: 'parking-pool-48cd9',
    storageBucket: 'parking-pool-48cd9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEEp9d3ZXivwcbWEciXTHVMY_WmzOT4UU',
    appId: '1:359537542451:ios:c92a8f58100cfce4c2aa46',
    messagingSenderId: '359537542451',
    projectId: 'parking-pool-48cd9',
    storageBucket: 'parking-pool-48cd9.firebasestorage.app',
    iosBundleId: 'com.example.parkingPool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEEp9d3ZXivwcbWEciXTHVMY_WmzOT4UU',
    appId: '1:359537542451:ios:c92a8f58100cfce4c2aa46',
    messagingSenderId: '359537542451',
    projectId: 'parking-pool-48cd9',
    storageBucket: 'parking-pool-48cd9.firebasestorage.app',
    iosBundleId: 'com.example.parkingPool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLwNX6Cr8OFRIOeogcM6x_5Sc1F-57nU0',
    appId: '1:359537542451:web:e86b4cb2a954bac4c2aa46',
    messagingSenderId: '359537542451',
    projectId: 'parking-pool-48cd9',
    authDomain: 'parking-pool-48cd9.firebaseapp.com',
    storageBucket: 'parking-pool-48cd9.firebasestorage.app',
    measurementId: 'G-23EHQ3SD9T',
  );
}
